// Generated by https://quicktype.io

export interface Character {
    char_id:                     number;
    name:                        string;
    birthday:                    string;
    occupation:                  string[];
    img:                         string;
    status:                      Status;
    nickname:                    string;
    appearance:                  number[];
    portrayed:                   string;
    category:                    Category;
    better_call_saul_appearance: number[];
    species:                     string;
    gender:                      string;
    house:                       string;
    dateOfBirth:                 string;
    yearOfBirth:                 number;
    wizard:                      boolean;
    ancestry:                    string;
    eyeColour:                   string;
    hairColour:                  string;
    wand: {
        wood:      string,
        core:      string,
        length:    number
    };
    patronus:                    string;
    hogwartsStudent:             boolean;
    hogwartsStaff:               boolean;
    actor:                       string;
    alive:                       boolean;
    image:                       string;
}

export enum Category {
    BetterCallSaul = "Better Call Saul",
    BreakingBad = "Breaking Bad",
    BreakingBadBetterCallSaul = "Breaking Bad, Better Call Saul",
}

export enum Status {
    Alive = "Alive",
    Deceased = "Deceased",
    PresumedDead = "Presumed dead",
    Unknown = "Unknown",
}